// This file is autogenerated. Do not edit.

namespace hash_checker{
    internal class Hashes{
        public static (string, string)[] HashesByPath = new (string, string)[]{
        };
    }
}
