name: Build Visual Studio Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore YourProject.sln

      - name: Build Solution
        run: msbuild Src/ClipboardFirewall.sln /p:Configuration=Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-Output
          path: '**/bin/Release/*'
