name: Build Visual Studio Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'
          msbuild-architecture: x86

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Src/ClipboardFirewall.sln

      - name: Compiling CFManualInjector..
        run: msbuild Src/CFManualInjector/CFManualInjector.vcxproj /p:Configuration=Release /p:Platform=x86 

      - name: Compiling ClipboardFirewallDll..
        run: msbuild Src/ClipboardFirewallDll/ClipboardFirewallDll.vcxproj /p:Configuration=Release /p:Platform=x86 /p:AdditionalIncludeDirectories="..\Deviare-InProc\Include"

      - name: Compiling InjectDll..
        run: msbuild Src/InjectDll/InjectDll.vcxproj /p:Configuration=Release /p:Platform=x86 /p:AdditionalIncludeDirectories="..\Deviare-InProc\Include"

      - name: Compiling code_generation..
        run: msbuild Src/code_generation/code_generation.vcxproj /p:Configuration=Release /p:Platform=x86 /p:AdditionalIncludeDirectories="..\Deviare-InProc\Include"

      - name: Compiling trayicon..
        run: msbuild Src/trayicon/trayicon.csproj /p:Configuration=Release /p:Platform=x86 /p:AdditionalIncludeDirectories="..\Deviare-InProc\Include"

      - name: Compiling ClipboardFirewallService..
        run: msbuild Src/ClipboardFirewallService/ClipboardFirewallService.vcxproj /p:Configuration=Release /p:Platform=x64 /p:AdditionalIncludeDirectories="..\Deviare-InProc\Include"


      - name: Compiling DriverInstaller..
        run: msbuild Src/DriverInstaller/DriverInstaller.vcxproj /p:Configuration=Release /p:Platform=x64 /p:AdditionalIncludeDirectories="..\Deviare-InProc\Include"


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Output
          path: '**/bin/Release/*'
